var LandName = [
'Acid',
'Advertisement',
'Age',
'Alloy',
'Alternation',
'Ambiance',
'Amusement',
'Angels',
'Annoyance',
'Apathy',
'Art',
'Ascent',
'Ash',
'Atoll',
'Autumn',
'Backstabbing',
'Bamboo',
'Bastille',
'Beauty',
'Blankness',
'Blaze',
'Boil',
'Bone',
'Books',
'Braille',
'Brains',
'Brick',
'Bridges',
'Bronze',
'Brooks',
'Bubbles',
'Bulge',
'Burlap',
'Butterflies',
'Cacophony',
'Cacti',
'Cages',
'Canopy',
'Canyons',
'Carbon',
'Carpet',
'Cathedrals',
'Caves',
'Chains',
'Change',
'Charge',
'Chemicals',
'Chocolate',
'Circuitry',
'Clay',
'Cliffs',
'Clockwork',
'Clouds',
'Cobalt',
'Cobblestone',
'Concrete',
'Construction',
'Contact',
'Contrast',
'Copper',
'Coral',
'Cotton',
'Crossroads',
'Crystal',
'Cubes',
'Curses',
'Dance',
'Dawn',
'Death',
'Decor',
'Depth',
'Descent',
'Desolation',
'Dew',
'Diamonds',
'Dirt',
'Disease',
'Dismay',
'Dolls',
'Dragons',
'Drought',
'Dungeons',
'Dust',
'Dye',
'Ebony',
'Echo',
'Eldritch',
'Electronics',
'Elegance',
'Emeralds',
'Evergreens',
'Falsehood',
'Fatigue',
'Fear',
'Festivities',
'Fire',
'Flame',
'Flow',
'Flowers',
'Fog',
'Forest',
'Fortification',
'Fossils',
'Freefall',
'Frost',
'Fungi',
'Fur',
'Gardens',
'Germs',
'Ghosts',
'Glamour',
'Glass',
'Glitter',
'Gloom',
'Glow',
'Glue',
'Gold',
'Graphite',
'Grass',
'Graves',
'Gravity',
'Gust',
'Hail',
'Hallucinations',
'Harbors',
'Hats',
'Hay',
'Haze',
'Heat',
'Hedges',
'Henge',
'Hills',
'Holes',
'Holly',
'Horror',
'Ice',
'Illusion',
'Ink',
'Insanity',
'Insomnia',
'Intimidation',
'Iron',
'Irradiation',
'Irrigation',
'Islands',
'Ivory',
'Jail',
'Jazz',
'Jokers',
'Jolliness',
'Jungle',
'Junk',
'Juxtaposition',
'Karaoke',
'Karate',
'Knowledge',
'Labyrinth',
'Ladders',
'Lakes',
'Lasers',
'Laugh',
'Law',
'Laze',
'Leaves',
'Levitation',
'Light',
'Loam',
'Luck',
'Magma',
'Magnets',
'Maps',
'Marsh',
'Meadow',
'Melody',
'Mercury',
'Mirrors',
'Mirth',
'Misers',
'Mist',
'Moss',
'Motion',
'Mountains',
'Mushrooms',
'Nails',
'Neon',
'Nickel',
'Night',
'Noir',
'Noise',
'Oasis',
'Obsidian',
'Odors',
'Oil',
'Opposites',
'Orchard',
'Ore',
'Paper',
'Paths',
'Pipes',
'Pistons',
'Plains',
'Plastic',
'Platforms',
'Pluck',
'Pollution',
'Portals',
'Powder',
'Prairie',
'Precipice',
'Presence',
'Presents',
'Prisms',
'Pulse',
'Pumpkins',
'Pyramids',
'Quakes',
'Quarry',
'Quartz',
'Rain',
'Rainbows',
'Ramps',
'Rays',
'Rebirth',
'Reflection',
'Regret',
'Repetition',
'Reversal',
'Rhythm',
'Rime',
'Rip',
'Rivers',
'Rock',
'Roses',
'Roses',
'Rot',
'Rubber',
'Rust',
'Sadness',
'Sand',
'Savannah',
'Scales',
'Science',
'Sentience',
'Shade',
'Shadow',
'Shattering',
'Shores',
'Shrines',
'Shrouds',
'Silence',
'Silhouette',
'Silk',
'Silt',
'Silver',
'Singe',
'Sketch',
'Skin',
'Sky',
'Slate',
'Slime',
'Sluice',
'Slumber',
'Snakes',
'Snow',
'Solace',
'Song',
'Spheres',
'Spices',
'Spikes',
'Spires',
'Sponge',
'Springs',
'Stability',
'Stairs',
'Static',
'Steam',
'Steel',
'Steppe',
'Storm',
'Strings',
'Stumps',
'Subway',
'Suction',
'Sulfur',
'Surprise',
'Swamp',
'Sweets',
'Tea',
'Teeth',
'Temples',
'Tents',
'Terror',
'Thorns',
'Thought',
'Thunder',
'Tin',
'Tinsel',
'Topiary',
'Trance',
'Tranquility',
'Transit',
'Traps',
'Travel',
'Treasure',
'Trove',
'Tundra',
'Tunnel',
'Turmoil',
'Twilight',
'Ultraviolence',
'Undead',
'Urns',
'Vacuum',
'Vapor',
'Variety',
'Veil',
'Velvet',
'Vibration',
'Vines',
'Walls',
'War',
'Warmth',
'Wasteland',
'Water',
'Waterfalls',
'Waves',
'Wax',
'Wheat',
'Wilderness',
'Wind',
'Windows',
'Womb',
'Wood',
'Wrath',
'Xenon',
'Yarn',
'Yore',
'Zen',
'Zephyr'
];

var TitleName1 = [
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Bard',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Heir',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Knight',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Mage',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Maid',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Page',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Prince',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Rogue',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Seer',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Sylph',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Thief',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
'Witch',
['Lord', 'Muse']
];

var LongTitleName1 = [
'Bane',
'Bard',
'Foe',
'Guide',
'Host',
'Knave',
'Knight',
'Mage',
'Monk',
'Page',
'Rogue',
'Sage',
'Spy',
'Sylph',
'Thane',
'Thief',
'Absolver',
'Ally',
'Archer',
'Chieftain',
'Cleric',
'Convict',
'Corporal',
'Druid',
'Ensign',
'Envoy',
'Forger',
'Hermit',
'Hero',
'Dealer',
'Hunter',
'Intern',
'Juror',
'Keeper',
'Marshal',
'Ninja',
'Noble',
'Nurse',
'Outlaw',
'Pirate',
'Poet',
'Proctor',
'Prophet',
'Pupil',
'Raider',
'Ranger',
'Rebel',
'Rival',
'Savior',
'Scourge',
'Scout',
'Scribe',
'Seeker',
'Seer',
'Shaman',
'Soldier',
'Squire',
'Stranger',
'Trainer',
'Usher',
'Vassal',
['Abbot', 'Abbess'],
['Baron', 'Baroness'],
['Count', 'Countess'],
['Duke', 'Duchess'],
['Heir', 'Heiress'],
['King', 'Queen'],
['Priest', 'Priestess'],
['Steward', 'Maid'],
['Wizard', 'Witch']
];

var TitleName2 = [
'Blood',
'Breath',
'Doom',
'Heart',
'Hope',
'Life',
'Light',
'Mind',
'Rage',
'Space',
'Time',
'Void'
];

var LongTitleName2 = [
'Action',
'Awesome',
'Balance',
'Bliss',
'Blood',
'Body',
'Breath',
'Caste',
'Cause',
'Chaos',
'Choice',
'Color',
'Cosmos',
'Courage',
'Dawn',
'Death',
'Depth',
'Doom',
'Dreams',
'Eclipse',
'Ego',
'Faith',
'Flesh',
'Form',
'Gale',
'Guile',
'Hate',
'Heart',
'Height',
'Honor',
'Hope',
'Imagination',
'Impact',
'Joy',
'Keys',
'Kindness',
'Law',
'Life',
'Light',
'Loss',
'Love',
'Madness',
'Might',
'Mind',
'Nature',
'Oath',
'Order',
'Peace',
'Power',
'Pulchritude',
'Purpose',
'Rage',
'Reason',
'Rhyme',
'Right',
'Season',
'Self',
'Shape',
'Sorrow',
'Soul',
'Sound',
'Space',
'Stars',
'Style',
'Time',
'Toil',
'Touch',
'Truth',
'Umbrage',
'Verve',
'Vim',
'Void',
'Wealth',
'Wisdom',
'Zeal'
];

var Chum1 = [
'acapella',
'ace',
'adios',
'analog',
'apocalypse',
'aquatic',
'arachnids',
'arcane',
'arduous',
'aristocratic',
'arsenic',
'caligulas',
'cannon',
'carapace',
'carcino',
'centaurs',
'concave',
'cuttlefish',
'graphical',
'guilded',
'gallows',
'garden',
'ghostly',
'golden',
'grayscale',
'grim',
'temporal',
'tentacle',
'textbook',
'tolerant',
'trivial',
'turntech',
'twin'
]

var Chum2 = [
'Countryman',
'Acupuncture',
'Adversary',
'Anatomy',
'Apothecary',
'Aquarium',
'Arisen',
'Armageddons',
'Assassin',
'Auxiliatrix',
'Calibrator',
'Capitalist',
'Catnip',
'Celebration',
'Culler',
'Gambler',
'Geneticist',
'Gnostic',
'Godhead',
'Grip',
'Guitarist',
'Taxonomist',
'Testicle',
'Testimony',
'Therapist',
'Toreador',
'Trickster',
'Troubadour',
'Typhoon'
];

var Interests = [
["Video Games", ["Metroid Prime", "Mario Figurine", "Minecraft", "Castlevania","The You Testament", "The Orange Box", "Shitty Roguelike burned to CD", "Sonic Plushtoy"]],
["Cooking", ["Saucepan", "Hot Sauce", "Cooking For Dummies", "Toaster", "Cooking Grease", "Ice Cream"]],
["Botany", ["Fertilizer", "Pumpkin", "Amorphophallus titanum", "Venus Fly Trap", "Tree Branch", "Watering Can"]],
["Art", ["Paintbrush", "Charcoal", "Pencil", "Creepy Figurine", "MC Escher Picture", "Giger Painting"]],
["Grimdark Arts", ["Summoning Grimoire", "Vial of your own blood", "Creepy Figurine", "'Username: 666' video, burned onto DVD", "Lovecraftian Novel", "Incense Holder", "Ectoplasm"]],
["Biology", ["Protein", "Crab Claw", "Genetic Horror", "Hazardous Chemicals", "Hologram of your own brain", "Fetus in a jar", "Taxidermied creature"]],
["Collectibles", ["Sonic Screwdriver", "Replica Lightsabre", "Tardis", "Dalek Figurine", "Miniature Stargate", "Spock Poster", "Transformer Action Figure", "Life-Sized Replica of the Millennium Falcon"]],
["Science", ["Tesla Coil", "Fusion Reactor", "Newton's Cradle", "Steampunk Novel", "Carbon Nanotube", "Vial of Mercury"]],
["Geology", ["Obsidian Stone", "Meteorite", "Diamond", "Geode", "Gold Leaf", "Interesting Stones"]],
["Engineering", ["Car Engine", "Plane Replica", "Car Battery", "Model Skyscraper"]],
["Frivolity", ["Wizard Hat", "Shitty Wizard Figurine", "Creepy Doll", "Trick Cards", "Whoopie Cushion", "Smoke Pellets", "Fake Blood Capsules", "Sassacre's Daunting Tome", "Magician's Gloves", "Clown Poster", "Unicycle", "Jack-in-the-Box", "Can-of-worms"]],
["Archaeology", ["Suit of Armor", "Mummy", "Sarcophagus", "Jade Figurine", "Indiana Jones Movie", "Dragon Figurine", "Toy Soldiers"]],
["Literature", ["Midsummer Night's Dream", "The Alchemist", "Chinese Haikus of Littler Historical Significance"]],
["Immaturity", ["Push-me Popper", "Teddy Bear", "Play-Doh", "Bouncy Ball"]],
["Sports", ["Football", "Baseball Glove", "Hockey Stick", "Tennis Racket"]],
["Warfare", ["Model Tank", "Ghilie Suit", "Night-vision Goggles", "Empty Magazine"]],
["Gambling", ["Playing Cards", "Poker Chips", "Roulette Wheel"]],
["Knick Knacks", ["Snow Globe", "Lava Lamp", "Miniature Eiffel Tower", "Plasma Globe", "Music Box"]],
["Paleontology", ["Fossilized Dinosaur Skin", "Preserved Amber", "Ammonite Shell", "T-Rex Tooth", "Footprint Fossil"]],
["Meta", ["SBHJ poster", "Con-Air Bunny", "Cool Horse Painting", "Problem Sleuth Poster", "Sepulchritude Shirt"]],	
];

var Specibi = [
["bladeKind", ["Bread Knife", "Sword", "Model Lightsabre", "2 Handed Sword", "Katana"]],
["pistolKind", ["Revolver", "Squirt Gun", "Nerf Gun", "Uzi", "Flare Gun"]],
["offcespplyKind", ["Stapler", "Staple Gun", "Ruler", "Scissors"]],
["gloveKind", ["Gloves", "Boxing Gloves", "Brass Knuckles"]],
["axeKind", ["Fire Axe", "Battleaxe", "Woodcutting Axe"]],
["fncysntaKind", ["Fancy Santa"]],
["whipKind", ["Dog Leash", "Wiimote", "1/2 bow", "Lasso", "Whip", "Leather Belt"]],
["hammerKind", ["Hammer", "Sledgehammer", "War Hammer"]],
["clubKind", ["Large Stick", "Baseball Bat", "Golf Club", "Night Stick"]],
["clawKind", ["Fake Fingernails", "Wolverine Claws", "Bagh Nakh"]],
["chainsawKind", ["Chainsaw"]],
["makeupKind", ["Lipstick"]],
["umbrellaKind", ["Umbrella"]],
["scytheKind", ["Farming Scythe", "Scythe"]],
["spearKind", ["Pointy Stick", "Spear", "Javelin", "Hawaiian Sling"]],
["wandKind", ["Shitty Wand", "Knitting Needles", "Twig"]],
["bowKind", ["Bow & Arrow", "Crossbow"]],
["diceKind", ["Pop-o-Matic", "Yahtzee Dice", "8 8-sided Dice"]],
["2*3dentKind", ["Trident", "Fork", "Pitchfork"]],
["guitarKind", ["Acoustic Guitar", "Electric Guitar", "12-String Guitar", "Ukulele"]],
["knifeKind", ["Steak Knife", "Pocket Knife", "Dagger", "Kukiri", "Sai"]],
["grenadeKind", ["Frag Grenades", "Smoke Grenades", "Flash Grenades", "Molotov Cocktails"]],
["staffkind", ["Pool Cue", "Bo Staff", "Quarterstaff"]],
["riflekind", ["Paintball Gun", "Machine Gun", "Shotgun", "Sniper Rifle", "Musket", "Harpoon Gun"]],
["maceKind", ["Mace", "Flail", "Morning Star", "Nunchucks"]],
["explosivesKind", ["Confetti Poppers", "Fireworks", "Dynamite", "C4", "Claymores"]],
["projectileKind", ["Darts", "Throwing Knives", "Shirukens", "Kunai"]],
["wrenchKind", ["Crescent Wrench", "Pipe Wrench", "Monkey Wrench", "Socket Wrench"]],
["screwdriverKind", ["Flathead Screwdriver", "Phillips Screwdriver", "Power Screwdriver", "Sonic Screwdriver toy"]]
];

var ConsortTypes = [
"alligators",
"anglerfish",
"ants",
"axolotls",
"bats",
"bears",
"bluebirds",
"canaries",
"cats",
"cougars",
"crocodiles",
"dogs",
"dolphins",
"doves",
"dragons",
"dugons",
"elephants",
"ferrets",
"foxes",
"gargoyles",
"giraffes",
"hamsters",
"humanimals",
"igaunas",
"kangaroos",
"lions",
"manatees",
"manticores",
"mice",
"minxes",
"monkeys",
"otters",
"owls",
"pandas",
"panthers",
"parrots",
"penguins",
"pigs",
"ponies",
"pterodactyls",
"rats",
"rhinos",
"salamanders",
"seagulls",
"sharks",
"snakes",
"squids",
"tigers",
"toucans",
"unicorns",
"velociraptors",
"vultures",
"walruses",
"whales",
"wolves",
"pandas",
"hawks",
"geckos",
"lemurs",
"chameleons",
"chickens",
"rabbits",
"weasels",
"griffons",
"badgers",
"snakes",
"beavers",
"cranes",
"skunks",
"hippos",
"turtles",
"sheep",
"racoons",
"ducks",
"moose",
"cows",
"camels"
];

var ConsortColors = [
"black",
"blue",
"fuschia",
"gold",
"green",
"hot pink",
"indigo",
"lavender",
"midnight blue",
"multi-colored",
"olive green",
"orange",
"pearl white",
"pink",
"red",
"silver",
"sky blue",
"steel grey",
"teal",
"violet",
"orange",
"white",
"yellow",
"forest green",
"translucent",
"vermillion",
"turquoise",
"cerulean",
"rainbow",
"cyan",
"magenta",
"mustard yellow",
"neon yellow",
"brown",
"beige"
];

var ConsortQuirks = [
"arrogant",
"awesome",
"depressed",
"easily distracted",
"eccentric",
"gullible",
"hyperactive",
"insulting",
"irrational",
"joyful",
"lazy",
"mysterious",
"shy",
"stupid",
"violent",
"warlike",
"weird",
"naive",
"timid",
"rambunctious",
"swindling",
"helpful",
"brazen",
"neurotic",
"impressionable",
"blithe",
"forgetful",
"concerningly sexy",
"uncoordinated"
];

var ConsortLikes = [
"architecture",
"art",
"beauty",
"friendship",
"gadgetry",
"knowledge",
"magic",
"mining",
"money",
"nature",
"politics",
"power",
"skateboarding",
"stories",
"tomfoolery",
"gemstones",
"science",
"exploration",
"adventure",
"agriculture",
"pranks",
"music",
"dancing",
"swimming",
"philosophy"
];

